<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <!--  This is the PARENT project  -->
    <!--  All child services will inherit these settings  -->
    <groupId>com.quickbite</groupId>
    <artifactId>quickbite-backend</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>  <!-- pom means this is a parent, not a runnable app -->

    <!--  Spring Boot parent gives us default versions for all libraries  -->
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.2.5</version>
        <relativePath/>
    </parent>

    <properties>
        <java.version>21</java.version>
        <jjwt.version>0.12.3</jjwt.version>
    </properties>

    <modules>
        <module>auth-service</module>
	<module>restaurant-service</module>
    </modules>

</project>