server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      # Global CORS
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      routes:

        # AUTH SERVICE
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            # No JWT needed for auth routes — public
            - name: RemoveRequestHeader
              args:
                name: Cookie

        # RESTAURANT SERVICE
        - id: restaurant-service
          uri: lb://restaurant-service
          predicates:
            - Path=/api/restaurants/**
          filters:
            - AuthenticationFilter

        # MENU SERVICE
        - id: menu-service
          uri: lb://menu-service
          predicates:
            - Path=/api/menu/**
          filters:
            - AuthenticationFilter

        # CART SERVICE
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/api/cart/**
          filters:
            - AuthenticationFilter

        # ORDER SERVICE
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
          filters:
            - AuthenticationFilter

        # NOTIFICATION SERVICE
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
          filters:
            - AuthenticationFilter

        # REVIEW SERVICE
        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/api/reviews/**
          filters:
            - AuthenticationFilter

# Eureka registration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# JWT secret — only needed here now
jwt:
  secret: quickbite_super_secret_key_2026_very_long_string_for_security
  expiration: 86400000