server.port=8083
spring.application.name=menu-service

spring.datasource.url=jdbc:mysql://localhost:3306/quickbite_menu?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=quickbite_super_secret_key_2026_very_long_string_for_security
jwt.expiration=86400000